server:
  port: 7071
spring:
  servlet:
    multipart:
      max-file-size: 10000MB
      max-request-size: 15000MB
  application:
    name: pilipala-web
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/pilipala?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    hikari:
      pool-name: HikariCPDatasource
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    database: 0
    host: 192.168.194.130
    password: gjx10086
    port: 6379
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 2000

mybatis:
  configuration:
    map-underscore-to-camel-case: true

project:
  folder: "D:\\Code\\workspace-teach\\pilipala Files\\"
log:
  root:
    level: debug
admin:
  account: admin
  password: admin123